<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC6F44Wn\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC6F44Wn/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerC6F44Wn.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerC6F44Wn\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerC6F44Wn\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'C6F44Wn',
    'container.build_id' => '5d78be77',
    'container.build_time' => 1518991334,
));
